### PR TITLE
docs: fix example; default import needs destructuring

### PR DESCRIPTION
**Pull request by foxxyz**
Fixes the example in the README, it does not work as-is.

Thanks for the package!

### CODE REVIEW

**Comment by RienNeVaPlus** [comment]
Thanks for the pull request. However, `humanId` is also the default export, see [here](https://github.com/RienNeVaPlus/human-id/blob/master/index.ts#L92). Can you elaborate, why this isn't working for you?

**Comment by foxxyz** [comment]
Sure. I was unable to run the example as-is:
```
> const humanId = await import('human-id')
undefined
> humanId()
Uncaught TypeError: humanId is not a function
>
```
I am using Node 19.6.0 with human-id `4.0.0`.

Inspecting shows:
```
> humanId
[Module: null prototype] {
  __esModule: true,
  adjectives: [...],
  adverbs: [...],
  default: {
    adjectives: [...],
    nouns: [...],
    verbs: [...],
    adverbs: [...],
    humanId: [Function: humanId],
    poolSize: [Function: poolSize],
    maxLength: [Function: maxLength],
    minLength: [Function: minLength],
    default: [Function: humanId]
  },
  humanId: [Function: humanId],
  maxLength: [Function: maxLength],
  minLength: [Function: minLength],
  nouns: [...],
  poolSize: [Function: poolSize],
  verbs: [...]
}
```

Is there something broken in the build toolchain maybe?

**Comment by RienNeVaPlus** [comment]
Dynamic imports work [a little different](https://javascript.info/modules-dynamic-imports), but I see your point and will merge this soon.

**Comment by foxxyz** [comment]
I'm only importing dynamically because I'm using the REPL.

I believe the outcome is the same doing a regular `import humanId from 'human-id'` or a cjs require:
```
> const humanId = require('human-id')
undefined
> humanId()
Uncaught TypeError: humanId is not a function
```

**Comment by RienNeVaPlus** [comment]
Solved

**Pull request closed without merging**
